export const SET_USER = 'SET_USER';
export const SET_POPUP_ACTIVE = 'SET_POPUP_ACTIVE';
export const ADD_CART_ITEMS = 'ADD_CART_ITEMS';
export const CLEAR_CART_ITEMS = 'CLEAR_CART_ITEMS';

export const FETCH_GOODS_STARTED = 'FETCH_GOODS_STARTED';
export const FETCH_GOODS_SUCCESS = 'FETCH_GOODS_SUCCESS';
export const FETCH_GOODS_ERROR = 'FETCH_GOODS_ERROR';

export const UPDATE_IN_STOCK_STARTED = 'UPDATE_IN_STOCK_STARTED';
export const UPDATE_IN_STOCK_SUCCESS = 'UPDATE_IN_STOCK_SUCCESS';
export const UPDATE_IN_STOCK_ERROR = 'UPDATE_IN_STOCK_ERROR';

export const FETCH_GOOD_STARTED = 'FETCH_GOOD_STARTED';
export const FETCH_GOOD_SUCCESS = 'FETCH_GOOD_SUCCESS';
export const FETCH_GOOD_ERROR = 'FETCH_GOOD_ERROR';

